### PR TITLE
fixed sanity tests for ims_command unit tests

### PR DESCRIPTION
**Pull request by oelbarmawi**
##### SUMMARY

Fixed anisble sanity test errors for the following folder
```
tests/units/modules/ims_command/
```

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Command "ansible-doc -t module ibm.ibm_zos_ims.ims_acb_gen ibm.ibm_zos_ims.ims_command ibm.ibm_zos_ims.ims_dbd_gen ibm.ibm_zos_ims.ims_psb_gen" returned exit status 1.
ERROR: Found 5 future-import-boilerplate issue(s) which need to be resolved:
ERROR: plugins/module_utils/acbgen.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: plugins/modules/ims_acb_gen.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:5:1: Line cannot be empty or contain only a comment
ERROR: Found 1 import issue(s) on python 3.7 which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:9:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package
ERROR: Found 1 import issue(s) on python 3.8 which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:9:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package
ERROR: Found 55 pep8 issue(s) which need to be resolved:
ERROR: plugins/module_utils/ims_gen_utils.py:13:94: E225: missing whitespace around operator
ERROR: plugins/module_utils/ims_gen_utils.py:13:131: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:24:21: E222: multiple spaces after operator
ERROR: plugins/module_utils/ims_gen_utils.py:31:104: E225: missing whitespace around operator
ERROR: plugins/module_utils/ims_gen_utils.py:34:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:37:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:41:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:48:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:55:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:71:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:85:57: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:93:42: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:93:51: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:100:61: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:107:61: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:115:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:124:75: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:124:91: E711: comparison to None should be 'if cond is not None:'
ERROR: plugins/module_utils/ims_gen_utils.py:126:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:264:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:293:47: E711: comparison to None should be 'if cond is None:'
ERROR: plugins/module_utils/ims_gen_utils.py:311:79: E203: whitespace before ':'
ERROR: plugins/module_utils/ims_gen_utils.py:331:58: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:331:67: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:346:25: E265: block comment should start with '# '
ERROR: plugins/module_utils/ims_gen_utils.py:363:29: E265: block comment should start with '# '
ERROR: plugins/module_utils/ims_gen_utils.py:415:77: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/ims_gen_utils.py:416:25: E128: continuation line under-indented for visual indent
ERROR: plugins/module_utils/ims_gen_utils.py:452:76: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/ims_gen_utils.py:453:25: E128: continuation line under-indented for visual indent
ERROR: plugins/module_utils/ims_gen_utils.py:513:49: W292: no newline at end of file
ERROR: plugins/module_utils/ims_module_error_messages.py:3:1: E302: expected 2 blank lines, found 0
ERROR: plugins/module_utils/ims_module_error_messages.py:6:161: E501: line too long (278 > 160 characters)
ERROR: plugins/module_utils/ims_module_error_messages.py:21:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_module_error_messages.py:41:83: W292: no newline at end of file
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:4:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:21:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:55:161: E501: line too long (172 > 160 characters)
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:70:43: E261: at least two spaces before inline comment
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:70:44: E262: inline comment should start with '# '
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:126:38: E712: comparison to False should be 'if cond is False:' or 'if not cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:276:111: W292: no newline at end of file
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:58:38: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:75:1: W391: blank line at end of file
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:84:38: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:234:84: W292: no newline at end of file
ERROR: tests/helpers/ztest.py:24:1: E302: expected 2 blank lines, found 1
ERROR: tests/helpers/ztest.py:65:24: W292: no newline at end of file
ERROR: tests/units/module_utils/test_ims_gen_utils.py:26:22: E261: at least two spaces before inline comment
ERROR: tests/units/module_utils/test_ims_gen_utils.py:28:22: E261: at least two spaces before inline comment
ERROR: tests/units/module_utils/test_ims_gen_utils.py:33:1: E302: expected 2 blank lines, found 0
ERROR: tests/units/module_utils/test_ims_gen_utils.py:37:1: E305: expected 2 blank lines after class or function definition, found 1
ERROR: tests/units/module_utils/test_ims_gen_utils.py:45:75: E226: missing whitespace around arithmetic operator
ERROR: tests/units/module_utils/test_ims_gen_utils.py:49:34: E231: missing whitespace after ':'
ERROR: tests/units/module_utils/test_ims_gen_utils.py:52:1: E302: expected 2 blank lines, found 0
ERROR: Found 29 pylint issue(s) which need to be resolved:
ERROR: plugins/module_utils/ims_gen_utils.py:13:130: bad-whitespace: Exactly one space required after comma     (conv_rc, stdout, stderr) = module.run_command('iconv -f ISO8859-1 -t IBM-1047 %s &gt; %s' %(ZOAUTIL_TEMP_USS, ZOAUTIL_TEMP_USS2),use_unsafe_shell=True)                                                                                                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:24:18: bad-whitespace: Exactly one space required after comparison         if stdout !=  '':                   ^^
ERROR: plugins/module_utils/ims_gen_utils.py:31:115: undefined-variable: Undefined variable 'result'
ERROR: plugins/module_utils/ims_gen_utils.py:43:8: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:43:32: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:50:8: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:50:32: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:57:4: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:57:36: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:93:41: bad-whitespace: Exactly one space required after comma             src_member, target_name = [(k,v) for k,v in member.items()][0]                                          ^
ERROR: plugins/module_utils/ims_gen_utils.py:93:50: bad-whitespace: Exactly one space required after comma             src_member, target_name = [(k,v) for k,v in member.items()][0]                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:124:11: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: plugins/module_utils/ims_gen_utils.py:124:74: bad-whitespace: Exactly one space required after comma     return re.fullmatch(r"^[A-Z$#@]{1}[A-Z0-9$#@]{0,7}$", str(member_name),re.IGNORECASE) != None                                                                           ^
ERROR: plugins/module_utils/ims_gen_utils.py:293:37: singleton-comparison: Comparison to None should be 'expr is None'
ERROR: plugins/module_utils/ims_gen_utils.py:311:47: unneeded-not: Consider changing "not not source['member_list']" to "source['member_list']"
ERROR: plugins/module_utils/ims_gen_utils.py:311:79: bad-whitespace: No space allowed before :                 if 'member_list' in source and not (not source['member_list']) :                                                                                ^
ERROR: plugins/module_utils/ims_gen_utils.py:331:57: bad-whitespace: Exactly one space required after comma                             src_member, target_name = [(k,v) for k,v in item.items()][0]                                                          ^
ERROR: plugins/module_utils/ims_gen_utils.py:331:66: bad-whitespace: Exactly one space required after comma                             src_member, target_name = [(k,v) for k,v in item.items()][0]                                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:513:0: missing-final-newline: Final newline missing
ERROR: plugins/module_utils/ims_module_error_messages.py:41:0: missing-final-newline: Final newline missing
ERROR: plugins/modules/ims_acb_gen.py:286:12: repeated-keyword: Got multiple values for keyword argument 'msg' in function call
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:126:15: singleton-comparison: Comparison to False should be 'not expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:276:0: missing-final-newline: Final newline missing
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:58:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:75:0: trailing-newlines: Trailing newlines
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:84:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:234:0: missing-final-newline: Final newline missing
ERROR: tests/helpers/ztest.py:13:0: syntax-error: Cannot import 'collections' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 96)'
ERROR: tests/helpers/ztest.py:65:0: missing-final-newline: Final newline missing
ERROR: Found 2 shebang issue(s) which need to be resolved:
ERROR: playbook.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
ERROR: tests/run.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
ERROR: Found 19 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package'
ERROR: plugins/modules/ims_acb_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_acb_gen.py:7:0: import-before-documentation: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA.
ERROR: plugins/modules/ims_acb_gen.py:91:7: documentation-syntax-error: DOCUMENTATION is not valid YAML
ERROR: plugins/modules/ims_command.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_command.py:0:0: return-syntax-error: RETURN.failed.type: not a valid value for dictionary value @ data['failed']['type']. Got 'boolean'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dbd_name' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dbd_name' in argument_spec found in batch defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dest' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'member_list' in argument_spec defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'member_list' in argument_spec found in batch defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'src' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'src' in argument_spec found in batch defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'sys_lib' in argument_spec defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: invalid-documentation: DOCUMENTATION.options.batch.suboptions.member_list.elements: not a valid value for dictionary value @ data['options']['batch']['suboptions']['member_list']['elements']. Got 'str or dict with single key-value pair'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: invalid-documentation: DOCUMENTATION.options.member_list.elements: not a valid value for dictionary value @ data['options']['member_list']['elements']. Got 'str or dict with single key-value pair'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_dbd_gen.py:0:0: return-syntax-error: RETURN.batch_result.returned: required key not provided @ data['batch_result']['returned']. Got None
ERROR: plugins/modules/ims_psb_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:91:7: error: DOCUMENTATION: syntax error: could not find expected ':' (syntax)
ERROR: The 10 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: script returned exit code 1

**Comment by IBMAnsibleHelper** [comment]
Exception: ansible-test detected errors! 
 ERROR: Command "ansible-doc -t module ibm.ibm_zos_ims.ims_acb_gen ibm.ibm_zos_ims.ims_command ibm.ibm_zos_ims.ims_dbd_gen ibm.ibm_zos_ims.ims_psb_gen" returned exit status 1.
ERROR: Found 5 future-import-boilerplate issue(s) which need to be resolved:
ERROR: plugins/module_utils/acbgen.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: plugins/modules/ims_acb_gen.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: Found 1 ignores issue(s) which need to be resolved:
ERROR: tests/sanity/ignore-2.9.txt:5:1: Line cannot be empty or contain only a comment
ERROR: Found 1 import issue(s) on python 3.7 which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:9:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package
ERROR: Found 1 import issue(s) on python 3.8 which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:9:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package
ERROR: Found 55 pep8 issue(s) which need to be resolved:
ERROR: plugins/module_utils/ims_gen_utils.py:13:94: E225: missing whitespace around operator
ERROR: plugins/module_utils/ims_gen_utils.py:13:131: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:24:21: E222: multiple spaces after operator
ERROR: plugins/module_utils/ims_gen_utils.py:31:104: E225: missing whitespace around operator
ERROR: plugins/module_utils/ims_gen_utils.py:34:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:37:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:41:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:48:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:55:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:71:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:85:57: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:93:42: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:93:51: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:100:61: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:107:61: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/ims_gen_utils.py:115:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:124:75: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:124:91: E711: comparison to None should be 'if cond is not None:'
ERROR: plugins/module_utils/ims_gen_utils.py:126:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:264:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_gen_utils.py:293:47: E711: comparison to None should be 'if cond is None:'
ERROR: plugins/module_utils/ims_gen_utils.py:311:79: E203: whitespace before ':'
ERROR: plugins/module_utils/ims_gen_utils.py:331:58: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:331:67: E231: missing whitespace after ','
ERROR: plugins/module_utils/ims_gen_utils.py:346:25: E265: block comment should start with '# '
ERROR: plugins/module_utils/ims_gen_utils.py:363:29: E265: block comment should start with '# '
ERROR: plugins/module_utils/ims_gen_utils.py:415:77: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/ims_gen_utils.py:416:25: E128: continuation line under-indented for visual indent
ERROR: plugins/module_utils/ims_gen_utils.py:452:76: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/ims_gen_utils.py:453:25: E128: continuation line under-indented for visual indent
ERROR: plugins/module_utils/ims_gen_utils.py:513:49: W292: no newline at end of file
ERROR: plugins/module_utils/ims_module_error_messages.py:3:1: E302: expected 2 blank lines, found 0
ERROR: plugins/module_utils/ims_module_error_messages.py:6:161: E501: line too long (278 > 160 characters)
ERROR: plugins/module_utils/ims_module_error_messages.py:21:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/ims_module_error_messages.py:41:83: W292: no newline at end of file
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:4:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:21:1: E302: expected 2 blank lines, found 1
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:55:161: E501: line too long (172 > 160 characters)
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:70:43: E261: at least two spaces before inline comment
ERROR: tests/functional/module_utils/ims_test_gen_utils.py:70:44: E262: inline comment should start with '# '
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:126:38: E712: comparison to False should be 'if cond is False:' or 'if not cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:276:111: W292: no newline at end of file
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:58:38: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:75:1: W391: blank line at end of file
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:84:38: E712: comparison to True should be 'if cond is True:' or 'if cond:'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:234:84: W292: no newline at end of file
ERROR: tests/helpers/ztest.py:24:1: E302: expected 2 blank lines, found 1
ERROR: tests/helpers/ztest.py:65:24: W292: no newline at end of file
ERROR: tests/units/module_utils/test_ims_gen_utils.py:26:22: E261: at least two spaces before inline comment
ERROR: tests/units/module_utils/test_ims_gen_utils.py:28:22: E261: at least two spaces before inline comment
ERROR: tests/units/module_utils/test_ims_gen_utils.py:33:1: E302: expected 2 blank lines, found 0
ERROR: tests/units/module_utils/test_ims_gen_utils.py:37:1: E305: expected 2 blank lines after class or function definition, found 1
ERROR: tests/units/module_utils/test_ims_gen_utils.py:45:75: E226: missing whitespace around arithmetic operator
ERROR: tests/units/module_utils/test_ims_gen_utils.py:49:34: E231: missing whitespace after ':'
ERROR: tests/units/module_utils/test_ims_gen_utils.py:52:1: E302: expected 2 blank lines, found 0
ERROR: Found 29 pylint issue(s) which need to be resolved:
ERROR: plugins/module_utils/ims_gen_utils.py:13:130: bad-whitespace: Exactly one space required after comma     (conv_rc, stdout, stderr) = module.run_command('iconv -f ISO8859-1 -t IBM-1047 %s &gt; %s' %(ZOAUTIL_TEMP_USS, ZOAUTIL_TEMP_USS2),use_unsafe_shell=True)                                                                                                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:24:18: bad-whitespace: Exactly one space required after comparison         if stdout !=  '':                   ^^
ERROR: plugins/module_utils/ims_gen_utils.py:31:115: undefined-variable: Undefined variable 'result'
ERROR: plugins/module_utils/ims_gen_utils.py:43:8: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:43:32: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:50:8: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:50:32: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:57:4: blacklisted-name: Black listed name "_"
ERROR: plugins/module_utils/ims_gen_utils.py:57:36: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/module_utils/ims_gen_utils.py:93:41: bad-whitespace: Exactly one space required after comma             src_member, target_name = [(k,v) for k,v in member.items()][0]                                          ^
ERROR: plugins/module_utils/ims_gen_utils.py:93:50: bad-whitespace: Exactly one space required after comma             src_member, target_name = [(k,v) for k,v in member.items()][0]                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:124:11: singleton-comparison: Comparison to None should be 'expr is not None'
ERROR: plugins/module_utils/ims_gen_utils.py:124:74: bad-whitespace: Exactly one space required after comma     return re.fullmatch(r"^[A-Z$#@]{1}[A-Z0-9$#@]{0,7}$", str(member_name),re.IGNORECASE) != None                                                                           ^
ERROR: plugins/module_utils/ims_gen_utils.py:293:37: singleton-comparison: Comparison to None should be 'expr is None'
ERROR: plugins/module_utils/ims_gen_utils.py:311:47: unneeded-not: Consider changing "not not source['member_list']" to "source['member_list']"
ERROR: plugins/module_utils/ims_gen_utils.py:311:79: bad-whitespace: No space allowed before :                 if 'member_list' in source and not (not source['member_list']) :                                                                                ^
ERROR: plugins/module_utils/ims_gen_utils.py:331:57: bad-whitespace: Exactly one space required after comma                             src_member, target_name = [(k,v) for k,v in item.items()][0]                                                          ^
ERROR: plugins/module_utils/ims_gen_utils.py:331:66: bad-whitespace: Exactly one space required after comma                             src_member, target_name = [(k,v) for k,v in item.items()][0]                                                                   ^
ERROR: plugins/module_utils/ims_gen_utils.py:513:0: missing-final-newline: Final newline missing
ERROR: plugins/module_utils/ims_module_error_messages.py:41:0: missing-final-newline: Final newline missing
ERROR: plugins/modules/ims_acb_gen.py:286:12: repeated-keyword: Got multiple values for keyword argument 'msg' in function call
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:126:15: singleton-comparison: Comparison to False should be 'not expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py:276:0: missing-final-newline: Final newline missing
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:58:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py:75:0: trailing-newlines: Trailing newlines
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:84:15: singleton-comparison: Comparison to True should be just 'expr'
ERROR: tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py:234:0: missing-final-newline: Final newline missing
ERROR: tests/helpers/ztest.py:13:0: syntax-error: Cannot import 'collections' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 96)'
ERROR: tests/helpers/ztest.py:65:0: missing-final-newline: Final newline missing
ERROR: Found 2 shebang issue(s) which need to be resolved:
ERROR: playbook.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
ERROR: tests/run.sh:1:1: unexpected non-module shebang: b'#!/bin/bash'
ERROR: Found 19 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'No module named 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen.acbgen'; 'ansible_collections.ibm.ibm_zos_ims.plugins.module_utils.acbgen' is not a package'
ERROR: plugins/modules/ims_acb_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_acb_gen.py:7:0: import-before-documentation: Import found before documentation variables. All imports must appear below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA.
ERROR: plugins/modules/ims_acb_gen.py:91:7: documentation-syntax-error: DOCUMENTATION is not valid YAML
ERROR: plugins/modules/ims_command.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_command.py:0:0: return-syntax-error: RETURN.failed.type: not a valid value for dictionary value @ data['failed']['type']. Got 'boolean'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dbd_name' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dbd_name' in argument_spec found in batch defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'dest' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'member_list' in argument_spec defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'member_list' in argument_spec found in batch defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'src' in argument_spec defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'src' in argument_spec found in batch defines default as (None) but documentation defines default as ('False')
ERROR: plugins/modules/ims_dbd_gen.py:0:0: doc-default-does-not-match-spec: Argument 'sys_lib' in argument_spec defines default as (None) but documentation defines default as (['False'])
ERROR: plugins/modules/ims_dbd_gen.py:0:0: invalid-documentation: DOCUMENTATION.options.batch.suboptions.member_list.elements: not a valid value for dictionary value @ data['options']['batch']['suboptions']['member_list']['elements']. Got 'str or dict with single key-value pair'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: invalid-documentation: DOCUMENTATION.options.member_list.elements: not a valid value for dictionary value @ data['options']['member_list']['elements']. Got 'str or dict with single key-value pair'
ERROR: plugins/modules/ims_dbd_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/ims_dbd_gen.py:0:0: return-syntax-error: RETURN.batch_result.returned: required key not provided @ data['batch_result']['returned']. Got None
ERROR: plugins/modules/ims_psb_gen.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: Found 1 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/ims_acb_gen.py:91:7: error: DOCUMENTATION: syntax error: could not find expected ':' (syntax)
ERROR: The 10 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Review by itsBryantP — APPROVED** [review]

**Pull request merged**
